[project]
name = "system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "chromadb>=1.0.17",
    "markdown>=3.8.2",
    "sentence-transformers>=5.1.0",
    "watchdog>=6.0.0",
]
